apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: produtos
  template:
    metadata:
      labels:
        app: produtos
    spec:
      containers:
        - name: produtos
          image: produtos-service:latest   # nome correto
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "dbname=shoopdb user=marco password=marco123 host=db-service port=5432"
