apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16              # nome igual ao docker-compose
          imagePullPolicy: IfNotPresent        # força usar a imagem local
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "marco"
            - name: POSTGRES_PASSWORD
              value: "marco123"
            - name: POSTGRES_DB
              value: "shoopdb"
