apiVersion: apps/v1
kind: Deployment
metadata:
  name: compras-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compras
  template:
    metadata:
      labels:
        app: compras
    spec:
      containers:
        - name: compras
          image: service-compras:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "dbname=shoopdb user=marco password=marco123 host=db-service port=5432"
