apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
        - name: pagamentos
          image: pagamentos:latest   # nome correto da imagem
          imagePullPolicy: Never               # não tenta puxar da internet
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "dbname=shoopdb user=marco password=marco123 host=db-service port=5432"
