apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoop-api
  template:
    metadata:
      labels:
        app: shoop-api
    spec:
      containers:
      - name: shoop-api
        image: sua-imagem:latest
        ports:
        - containerPort: 8080
